Convert to Vue.js frontend
Police-Data-Accessibility-Project/pdap.io pull request #134
Opened 2023-10-08 16:27 UTC by benpolinsky

Convert pdap.io to Vue.js site.

Each static `*.html` page's unique content now resides in `src/views`. Repeatable sections of the site have been extracted as components to `src/components`. Most external scripts (Google Analytics, Font Awesome, etc...) reside in the main `index.html` file at the root of the repo. The `sitemap.xml` and `robots.txt` files have been moved to `/public` so they are bundled appropriately for production builds.

Usage of assets from `pdap-design-system` is through standard node package management, i.e. `pnpm install`. When building for production, the scripts/assets from this package will be bundled along with the app - there should be no `node_modules` or `package-*` files residing on the production server.

Copyright is dynamically generated in the footer.

I am not sure how you are deploying the application, but you should now deploy the `dist` directory after building the site for production. This could be automated using GitHub Actions, most likely. You also may have to adjust your web server configuration so URLs are forwarded to Vue's router. If you let me know which web server is used (`nginx` for instance) I can advise.

Lastly, I've deployed a preview to Vercel: https://pdap-quu4kcobv-benjaminpolinsky.vercel.app/

2023-10-10 17:22 UTC, josh-chamberlain commented
thanks, @benpolinsky ! I'm going to pass this to @mbodeantor to make sure it passes our test—the timing on the rest of our Vue work might mean this needs to wait (or merge ahead of) the other stuff going on. We'll keep in touch.

2023-10-11 13:37 UTC, benpolinsky commented
> thanks, @benpolinsky ! I'm going to pass this to @mbodeantor to review and merge—the timing on the rest of our Vue work might mean this needs to wait (or merge ahead of) the other stuff going on. We'll keep in touch.

Great. No problem if anything needs to be adjusted to fit into what you have planned.

2023-10-17 13:38 UTC, joshuagraber requested changes
Hey, @benpolinsky, really nice work here, thank you.
Looks great, just a couple of small architectural changes, then g2g. (Also I'm seeing some merge conflicts, so please make sure any updates to markup from recent merges are reflected in your changes.)

2023-10-17 13:38 UTC, joshuagraber commented on package.json
Could you add an `"engines"` field here and provide the minimum `node` version required? In the absence of a tool like `nvm` (for now), this will communicate to developers which `node` version they'll need to install. If you need to check the minimum node versions required by the dependencies, run this command from the root dir.

```
find . -name package.json | xargs grep -h node\": | sort | uniq -c
```

 What you add to `"engines": {"node": "VERSION"}` should be >= the highest version of `node` printed to the console.

2023-10-17 13:38 UTC, joshuagraber commented on tsconfig.json
I really, _really_ like TS. But in my opinion, it's a premature optimization for this application, since it's more or less a static site, and we don't have any custom data types we need to keep straight. Would you mind converting to JS?

2023-10-17 13:38 UTC, joshuagraber commented on pnpm-lock.yaml
I think we want to be agnostic around which package manager developers use until we have a good reason to specify one. Would you mind removing this from version control and adding `pnpm-lock`, `package-lock`, and `yarn-lock` file patterns to the `.gitignore`?

2023-10-18 22:15 UTC, benpolinsky commented on tsconfig.json
Sure that makes sense to me.

2023-10-18 22:36 UTC, benpolinsky commented on pnpm-lock.yaml
I am split on this. On the one hand, good semantic versioning in the `package.json` _should_ ensure new developers don't have an issue when installing for the first time. On the other hand, not sure about upstream dependencies. 

I'm a big fan of not using something until it is necessary, too. But this _feels_ wrong to me. The guidance is nearly unanimous that the `package-lock.json` should be committed. In addition, there's no guarantee that every package manager will work well with the project just because we don't add a lock file. Choosing one manager (and committing the lock file) tells developers, "We know this is going to work out of the box for you." For instance, pnpm 8 made the questionable decision to install the least compatible version of a dependency's semver policy to [great community outrage](https://github.com/pnpm/pnpm/issues/6463). (This was [Eventually reversed](https://github.com/pnpm/pnpm/pull/6987)). 

Lastly, in my experience it's not too tough to switch package managers should the need arise. I can understand not wanting to use pnpm off the bat, but how about plain ol' npm?

Sorry for the essay! I have no issue ignoring all lock files if you've thought this through and that's the way you want to go.

2023-10-19 16:17 UTC, josh-chamberlain commented on pnpm-lock.yaml
Thanks for the thoughtful reply @benpolinsky ! I see the value in committing to a package manager, and `npm` is a more sensible default. I think folks can still use a different one if they want to, right? (deferring to @joshuagraber though)

2023-10-21 17:05 UTC, benpolinsky commented on package.json
FYI node 16.x is just out of LTS maintenance. I did add it for now, but perhaps 18.x is better way to go?

2023-10-21 17:06 UTC, benpolinsky commented on tsconfig.json
done

2023-10-21 17:07 UTC, benpolinsky commented on pnpm-lock.yaml
Moved to `npm`. Folks could still use what they would like, but they'd have to delete the `package-lock.json` file. I don't want to hold anything up, so if you'd like me to ignore the lock file so you move on, that's fine.

2023-10-23 18:06 UTC, joshuagraber commented on package.json
Yeah, @benpolinsky good callout. let's bump to `18`.

2023-10-23 18:07 UTC, joshuagraber commented on pnpm-lock.yaml
Yes, good points here @benpolinsky and I agree that `npm` makes sense as the default.

2023-10-27 16:43 UTC, josh-chamberlain commented on package.json
@joshuagraber are you down to pick an `18` version you like? I think that's about the last thing that needs resolution.

2023-10-27 16:45 UTC, josh-chamberlain approved these changes
pending resolving that last comment above this lgtm

2023-10-27 17:26 UTC, benpolinsky commented on package.json
Done - apologies for the wait. Work, life, etc :)

2023-10-27 20:09 UTC, merged