Add metrics to the site
Police-Data-Accessibility-Project/pdap.io pull request #177
Opened 2024-07-18 20:17 UTC by ecmcclain

**/ metrics**
![Screenshot 2024-07-18 at 3 19 39 PM](https://github.com/user-attachments/assets/fa59f0ca-b219-458b-b87a-ae5203291ac7)

**/data metrics:** 
![Screenshot 2024-07-18 at 3 19 23 PM](https://github.com/user-attachments/assets/b1b36828-61d6-41b0-8fcc-dd25bcd93e1e)
NOTE: These metrics are slow to load from the data sources API—any idea how I could make it faster?

**/community metrics**
![Screenshot 2024-07-18 at 3 21 05 PM](https://github.com/user-attachments/assets/2954448c-6065-431a-97eb-f88c3a64ee9e)

2024-07-23 15:53 UTC, josh-chamberlain requested changes
@ecmcclain Sorry about my delayed response. this is looking great! I like the text and icons you chose + generally how these look. I will probably suggest some copy edits before merge, but for now:

1. your email and password are exposed in the DataView; once you get your API key (by logging in), we should be able to just use that. We will use a different key when deployed to production
   - can you use the API to reset your password too? we don't want any impersonators...

2. could you add a note to the README about which `.env` variables are required for local development? (fig 1)

3. For slow-loading components—we have part of the solution figured out in the [design system](https://github.com/Police-Data-Accessibility-Project/design-system). If you run the dev version, you can see some shimmer classes in action (fig 2). We may need to update the design system version, but I'm not sure.

There's more info about [lazy loading in vue here](https://router.vuejs.org/guide/advanced/lazy-loading.html).

Ideally the dynamic components would be as small as possible, so the header and surrounding context would be visible. 

4. I sent you a Donorbox API key, and their [docs are here](https://github.com/donorbox/donorbox-api), for the donors metrics.


## fig 1
<img width="867" alt="Screen Shot 2024-07-23 at 11 32 26 AM" src="https://github.com/user-attachments/assets/3eded8f3-439f-4011-b816-34d0e2fab892">

## fig 2 
<img width="919" alt="Screen Shot 2024-07-23 at 11 35 46 AM" src="https://github.com/user-attachments/assets/e3314262-ae38-4a9e-a9af-0997cd9eb457">

2024-09-06 21:09 UTC, ecmcclain commented
TODO:
-on /donate finish the DonorBox API connection

For the Airtable API: I am not sure if using the "status (depreciated)" to find completed data requests will cause issues down the line if we are no longer tracking the progress of data requests in this way?

2024-09-10 17:09 UTC, josh-chamberlain commented
@ecmcclain ok, this is looking great! I know it must have been a fair amount of work to do the design system migration alone.

1. for `requests`, and `data sources`, I wonder if you could switch to using the v2 API: https://data-sources-v2.pdap.io/api
   - we have added a `requests` endpoint to the dev branch, but not to main yet (we can do that soon)
2. > For the Airtable API: I am not sure if using the "status (depreciated)" to find completed data requests will cause issues down the line if we are no longer tracking the progress of data requests in this way?
   - true...github will be the source of truth for requests. you could either use our new API as mentioned in point 1, or potentially use the github API: https://github.com/orgs/Police-Data-Accessibility-Project/projects/26
      - the advantage of this is that you wouldn't have to worry about what to count; if it's in there, it counts
   - we will sync project status from GitHub as part of a v2 issue, but we don't do that yet. https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/299
3. our donorbox email is operations@pdap.io

sorry about the change up in strategy for getting these! LMK if that makes sense.

2024-10-03 18:31 UTC, josh-chamberlain approved these changes
Merging this because I need to work on the site, and this fixes two issues! We can circle back in https://github.com/Police-Data-Accessibility-Project/pdap.io/issues/183

2024-10-03 18:32 UTC, merged